/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tomoarrow.idv.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: US,UK,CA,JP,UNKNOWN
 */
@Serializable
enum class Country(val value: kotlin.String) {

    @SerialName(value = "us")
    US("us"),

    @SerialName(value = "uk")
    UK("uk"),

    @SerialName(value = "ca")
    CA("ca"),

    @SerialName(value = "jp")
    JP("jp"),

    @SerialName(value = "unknown")
    UNKNOWN("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Country) "$data" else null

        /**
         * Returns a valid [Country] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Country? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


