/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tomoarrow.idv.client.models

import com.tomoarrow.idv.client.models.LiquidIdvField

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId 
 * @param fields 
 */
@Serializable

data class LiquidGetKycReq (

    @SerialName(value = "user_id")
    val userId: kotlin.String,

    @SerialName(value = "fields")
    val fields: kotlin.collections.List<@Contextual LiquidIdvField>? = null

) {


}

