/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tomoarrow.idv.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tomoarrow.idv.client.models.GoogleStartResp

class GoogleStartRespTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GoogleStartResp
        //val modelInstance = GoogleStartResp()

        // to test the property `authorizationUrl`
        should("test authorizationUrl") {
            // uncomment below to test the property
            //modelInstance.authorizationUrl shouldBe ("TODO")
        }

    }
}
