/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tomoarrow.idv.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tomoarrow.idv.client.models.LoginTicketRequest

class LoginTicketRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LoginTicketRequest
        //val modelInstance = LoginTicketRequest()

        // to test the property `bizToken`
        should("test bizToken") {
            // uncomment below to test the property
            //modelInstance.bizToken shouldBe ("TODO")
        }

        // to test the property `loginTicket`
        should("test loginTicket") {
            // uncomment below to test the property
            //modelInstance.loginTicket shouldBe ("TODO")
        }

    }
}
