/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tomoarrow.idv.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tomoarrow.idv.client.models.TomoIdvMockGetResultReq

class TomoIdvMockGetResultReqTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TomoIdvMockGetResultReq
        //val modelInstance = TomoIdvMockGetResultReq()

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

    }
}
